# Generated by Django 4.2.2 on 2023-06-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
