# Generated by Django 4.2.2 on 2023-06-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
