# Generated by Django 4.2.2 on 2023-07-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0004_alter_subcategory_parent_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
