# Generated by Django 4.2.2 on 2023-07-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0005_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_image',
        ),
    ]
