# Generated by Django 4.2.2 on 2023-07-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_category', '0006_remove_category_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_available',
        ),
    ]
